#!/bin/sh
DIM='\e[2m'
GREEN='\e[32m'
RED='\e[31m'
PLAIN='\e[0m'

abort_message="${RED}Commit aborted.${PLAIN}\n"
hook_name=`basename $0`
if [ -f ../../.git/hooks/personal/$hook_name ]
then
  if ! ../../.git/hooks/personal/$hook_name $@
  then
    printf ".git/hooks/personal/$hook_name failed\n"
    printf "$abort_message"
    exit 1
  fi
fi

branch_name=$(git branch | grep '*' | sed 's/* //')
if [[ $branch_name =~ 'no branch' ]]
then
  exit 0
else
  
  if ! grunt jshint
  then
    printf "$abort_message"
    exit 1
  fi
fi
